#cargo-features = ["nonzero_internals"]

[package]
name = "rhilbert"
version = "0.1.0"
edition = "2021"
authors = ["Chuck Ocheret"]

[dependencies]
num-traits = "0.2.19"
num-bigint = "0.4.6"
num-integer = "0.1.46"